// Environment variables (passed through the Cloudflare Workers Env)
declare let __COMPANY_NAME__: string
declare let __DOMAIN__: string
declare let __IMAP_HOST__: string
declare let __IMAP_PORT__: number
declare let __POP_HOST__: string
declare let __POP_PORT__: number
declare let __SMTP_HOST__: string
declare let __SMTP_PORT__: number
declare let __MOBILESYNC_URL__: string
declare let __LDAP_HOST__: string
declare let __LDAP_PORT__: number
declare let __LDAP_SOCKET__: string
declare let __LDAP_BASE__: string
declare let __LDAP_USER_FIELD__: string
declare let __LDAP_USER_BASE__: string
declare let __PROFILE_IDENTIFIER__: string
declare let __PROFILE_UUID__: string
declare let __MAIL_UUID__: string
declare let __LDAP_UUID__: string
declare let __IMAP_SOCKET__: string
declare let __POP_SOCKET__: string
declare let __SMTP_SOCKET__: string
declare let __MOBILESYNC_NAME__: string
declare let __LDAP_SEARCH__: string
declare let __SUPPORT_URL__: string
