// Environment variables (passed through the Cloudflare Workers Env)
declare var __COMPANY_NAME__: string
declare var __DOMAIN__: string
declare var __IMAP_HOST__: string
declare var __IMAP_PORT__: number
declare var __POP_HOST__: string
declare var __POP_PORT__: number
declare var __SMTP_HOST__: string
declare var __SMTP_PORT__: number
declare var __MOBILESYNC_URL__: string
declare var __LDAP_HOST__: string
declare var __LDAP_PORT__: number
declare var __LDAP_SOCKET__: string
declare var __LDAP_BASE__: string
declare var __LDAP_USER_FIELD__: string
declare var __LDAP_USER_BASE__: string
declare var __PROFILE_IDENTIFIER__: string
declare var __PROFILE_UUID__: string
declare var __MAIL_UUID__: string
declare var __LDAP_UUID__: string
declare var __IMAP_SOCKET__: string
declare var __POP_SOCKET__: string
declare var __SMTP_SOCKET__: string
declare var __MOBILESYNC_NAME__: string
declare var __LDAP_SEARCH__: string
declare var __SUPPORT_URL__: string
